sudo: true
os: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:

- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=0
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid 3MVG9fTLmJ60pJ5K6iXUWEO7ayo5OoK_XBN41.crnF85jT9dRK.9Rx4KfzAEIMQkNIE6InO37DaQt3aYnn6.M --username andrey.willi@gmail.com --jwtkeyfile assets/servwiki.key --setdefaultdevhubusername -r https://wandrey-dev-ed.my.salesforce.com
script:
- sfdx force:org:list --all
- sfdx force:org:create --definitionfile config/project-scratch-def.json --targetdevhubusername andrey.willi@gmail.Com --setalias my-scratch-org
- sfdx force:org:display -u my-scratch-org
- sfdx force:source:push -u my-scratch-org
- sfdx force:apex:test:run -u my-scratch-org --wait 10
- sfdx force:org:delete -u my-scratch-org -p -v andrey.willi@gmail.com


